### ISSUE TITLE
urlencode doesn't work

### ISSUE THREAD

**Issue by onereik** [HikaShop/hikapi#1]
Hello, 

I just noticed the URL encode doesn't work, for example, if I am getting a variable value of a password and since passwords could include special characters, the string has to be urlencod-ed in that matter, it returns invalid request.

**Comment by obsidev** [comment]
Hello,

Would it be possible to have more details about the context ?
Being able to reproduce the issue will help us to understand and provide the most appropriate fix.

For what I can see right now, sending the data in the POST with a "json encode" do not generate issues with the decode and do not require to perform a urlencode/urldecode ; even if there are special characters because they are handle by the JSON encoding.
So, having more details about your usage will definitively help

**Comment by onereik** [comment]
Hi, 

Thank you for the prompt reply. 

Well I am developing a mobile app relying on this api, the link has to send the username and password, lets say for example: http://localhost/hikashop-project/hikapi/login/:username/:password

The /:password part, for example insert special characters in the url like me@password 

Now because of @ the url will break and if it is url encoded it will become like this me%40password

In this case it is returning invalid request because the url can not have special characters, however when it is encoded it is still returning invalid request. 

I hope that was helpful, please let me know if you still have any questions or if anything is not clear. 

I look forward to hearing from you

Cheers

**Comment by obsidev** [comment]
Okay ! Thanks for the context

So, I suppose that you want to modify the line 147 of the HikApiHelper
https://github.com/HikaShop/hikapi/blob/master/plg_system_hikapi/hikapihelper.php#L147
And have instead :
`$params[$name] = urldecode($matches[$key + 1]);`

Regards,

**Comment by onereik** [comment]
Thanks, 

but that didn't really solve the problem! you try that yourself and try to insert any special characters in the url or insert it as an encoded string and see how it returns an invalid request

**Comment by onereik** [comment]
Obsidev, 

I will send you an email with a url so you can see that by yourself.

I am sending to the email you have on github

Thanks

**Comment by onereik** [comment]
Obsidev, 

I just sent you an email with a url. 

Let me know how it goes. 

Thanks
